const endpoint = (method, path, summary, input = 'None', access = 'public') => ({
  method,
  path,
  summary,
  input,
  access,
});

export const apiCatalog = Object.freeze({
  name: 'RiskRadar API',
  version: '1.0.0',
  description: 'UK postcode, point, and polygon crime intelligence API.',
  authentication: 'Public routes require no key. Admin routes require x-api-key or Authorization: Bearer.',
  endpoints: Object.freeze([
    endpoint('GET', '/health', 'Return runtime, cache, storage, rate-limit, and route diagnostics.'),
    endpoint('GET', '/ready', 'Return 200 when the service is ready to accept traffic.'),
    endpoint('GET', '/api/docs', 'Return this machine-readable endpoint catalogue.'),
    endpoint('GET', '/api/filter-metadata', 'List supported months, crime categories, and default radii.'),
    endpoint('POST', '/api/analyze-postcode', 'Build a complete postcode or place risk analysis.', '{ postcode|string query }'),
    endpoint('POST', '/api/analyze-point', 'Build a complete analysis centred on map coordinates.', '{ latitude, longitude, monthCount? }'),
    endpoint('POST', '/api/analyze-area', 'Build a complete analysis for a polygon.', '{ label?, points[3+], month?, categories? }'),
    endpoint('POST', '/api/compare-postcodes', 'Compare and rank up to five postcodes or places.', '{ postcodes[] }'),
    endpoint('POST', '/api/compare-points', 'Compare and rank up to five coordinate targets.', '{ points[] }'),
    endpoint('POST', '/api/compare-areas', 'Compare and rank up to five polygons.', '{ areas[] }'),
    endpoint('POST', '/api/postcode-crimes', 'Return filtered street incidents around a postcode.', '{ postcode|string query, month?, radiusMeters?, categories? }'),
    endpoint('POST', '/api/point-crimes', 'Return filtered street incidents inside a point radius.', '{ latitude, longitude, month?, radiusMeters?, categories? }'),
    endpoint('POST', '/api/location-crimes', 'Return incidents at the nearest exact police-mapped location.', '{ latitude, longitude, month?, categories? }'),
    endpoint('POST', '/api/area-crimes', 'Return filtered incidents inside a polygon.', '{ points[3+], month?, categories? }'),
    endpoint('POST', '/api/postcode-intelligence', 'Return postcode analysis, feeds, hotspots, and nearby postcodes.', '{ postcode|string query, month?, categories?, radiusMeters? }'),
    endpoint('POST', '/api/point-intelligence', 'Return point analysis, exact feed, hotspots, boundary, and nearby postcodes.', '{ latitude, longitude, month?, categories?, radiusMeters? }'),
    endpoint('POST', '/api/area-intelligence', 'Return polygon analysis, feed, hotspots, and nearby postcodes.', '{ label?, points[3+], month?, categories? }'),
    endpoint('POST', '/api/map-feed', 'Return a unified postcode, point, or area incident feed.', '{ mode: postcode|point|area, target fields, filters? }'),
    endpoint('POST', '/api/map-intelligence', 'Return unified intelligence for postcode, point, or area mode.', '{ mode: postcode|point|area, target fields, filters? }'),
    endpoint('POST', '/api/map-compare', 'Compare targets using a unified map mode.', '{ mode: postcode|point|area, targets }'),
    endpoint('POST', '/api/map-hotspots', 'Cluster filtered incidents around a postcode or inside a polygon.', '{ postcode|points, month?, categories?, maxClusters? }'),
    endpoint('POST', '/api/monthly-crime-series', 'Return ordered monthly totals, category series, and data-quality metadata.', '{ postcode|points, monthCount?, categories? }'),
    endpoint('GET', '/api/point-boundary', 'Return the official police neighbourhood boundary around coordinates.', 'Query: lat, lng'),
    endpoint('GET', '/api/location-suggestions', 'Return nearby postcodes for device coordinates.', 'Query: lat, lng'),
    endpoint('GET', '/api/crime-source-status', 'Describe the active live or local-file crime source.'),
    endpoint('GET', '/api/crime-dataset-summary', 'Summarise imported local crime snapshot coverage.', 'Query: month?, monthLimit?'),
    endpoint('GET', '/api/crime-score-calibration', 'Summarise score bands across imported local data.', 'Query: month?, limit?'),
    endpoint('GET', '/api/recent-analyses', 'List persisted analysis snapshot summaries.', 'Query: type?, limit?'),
    endpoint('GET', '/api/analysis-snapshot', 'Return a persisted analysis snapshot.', 'Query: id'),
    endpoint('DELETE', '/api/analysis-snapshot', 'Delete a persisted analysis snapshot.', 'Query: id'),
    endpoint('GET', '/api/search-presets', 'List saved search presets.', 'Query: type?, limit?'),
    endpoint('POST', '/api/search-presets', 'Create a reusable search preset.', '{ type, label, payload }'),
    endpoint('GET', '/api/search-preset', 'Return one saved search preset.', 'Query: id'),
    endpoint('DELETE', '/api/search-preset', 'Delete one saved search preset.', 'Query: id'),
    endpoint('POST', '/api/run-search-preset', 'Run a saved preset in analysis or feed mode.', '{ id, mode? }'),
    endpoint('GET', '/api/admin/state-export', 'Export persisted backend state.', 'Query: includeUpstreamCache?', 'admin'),
    endpoint('POST', '/api/admin/state-import', 'Import or merge persisted backend state.', '{ mode: replace|merge, stores }', 'admin'),
    endpoint('POST', '/api/admin/state-clear', 'Clear selected persisted backend stores.', '{ upstreamCache?, analysisSnapshots?, analysisCache?, searchPresets? }', 'admin'),
  ]),
});
